<?php

define('CURRENCIES_URL', 'http://www.nbrb.by/Services/XmlExRates.aspx');

use GuzzleHttp\Client;

/**
 * Returns all currencies.
 */
function lesson3_currencies_load($date = NULL) {
  $cache = &drupal_static(__FUNCTION__, array());
  $date = empty($date) ? date('m/d/Y', REQUEST_TIME) : $date;

  if (empty($cache[$date])) {
    $cache[$date] = FALSE;
    $client = new Client();
    $response = $client->get(CURRENCIES_URL, array(
      'query' => array(
        'ondate' => $date,
       ),
    ));

    if ($response->getStatusCode() == 200) {
      $data = $response->getBody()->getContents();
      $xml = simplexml_load_string($data);
      if ($xml) {
        $cache[$date] = array();
        foreach ($xml as $currency) {
          $code = $currency->CharCode->__toString();
          $cache[$date][$code] = new \stdClass();
          foreach ($currency->children() as $key => $value) {
            $cache[$date][$code]->{$key} = (string) $value;
          }
          $cache[$date][$code]->RateScaled = $cache[$date][$code]->Rate / $cache[$date][$code]->Scale;
        }
      }
    }
  }

  return $cache[$date];
}
